base_model: Qwen/Qwen2-1.5B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: lodrick-the-lafted/NopmWritingStruct
  - type: sharegpt
    conversation: chatml
  - path: kalomaze/Opus_Instruct_25k
  - type: sharegpt
    conversation: chatml
  - path: kalomaze/Opus_Instruct_3k
  - type: sharegpt
    conversation: chatml
  - path: MangoHQ/Claude-Data-Anon-Killed
  - type: sharegpt
    conversation: chatml
  - path: MangoHQ/Gryphe-3.5-16k-Subset
  - type: sharegpt

chat_template: chatml
dataset_prepared_path:
val_set_size: 0.05
output_dir: ./outputs/out
sequence_len: 16384
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

adapter:
lora_model_dir:
lora_r:
lora_alpha:
lora_dropout:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: Aleah-1.5B
wandb_entity:
wandb_watch:
wandb_name: Aleah1.5B
wandb_log_model:

gradient_accumulation_steps: 64
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.00002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_ratio: 0.05
evals_per_epoch: 4
saves_per_epoch: 1
debug:
weight_decay: 0.0
special_tokens:
