base_model: ./outputs/out
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: xh570j.jsonl
#    type:
#      system_prompt: ""
#      system_format: "<|im_start|>system\n{system}<|im_end|>\n"
#      field_system: instruction
#      field_instruction: input
#      field_input: ""
#      field_output: output
#      no_input_format: "<|im_start|>user\n{instruction}<|im_end|>\n<|im_start|>assistant\n"

#      system_prompt: ""
#      field_instruction: instruction
#      field_input: input
#      field_output: output
#      format: |-
#        <|im_start|>system
#        {instruction}<|im_end|>
#        <|im_start|>user
#        {input}<|im_end|>
#        <|im_start|>assistant
#        {output}

    type: alpaca
    conversation: mpt-30b-instruct
#    field_system: instruction
#    field_instruction: input
#    field_input: input
#    field_output: output

#  - path: kalomaze/Opus_Instruct_25k
#    type: sharegpt
#    conversation: mpt-30b-instruct

chat_template: alpaca

dataset_prepared_path:
val_set_size: 0.05
output_dir: ./outputs/out2
sequence_len: 2048
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

adapter:
lora_model_dir:
lora_r:
lora_alpha:
lora_dropout:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: Mango-SDprompt-qwenfinal
wandb_entity:
wandb_watch:
wandb_name: qwen1.5b-2
wandb_log_model:

gradient_accumulation_steps: 64
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_ratio: 0.2
evals_per_epoch: 4
saves_per_epoch: 1
debug:
weight_decay: 0.0
special_tokens:
